[tool.poetry]
name = "tope"
version = "0.2.0"
description = "Do stuff with 4d polytopes"
authors = ["Andrew <mail@awmacpherson.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.17.5"
pypoman = "^0.5.4"
loguru = "^0.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = ["."]
