[tool.poetry]
name = "tope"
version = "0.1.0"
description = "Do stuff with 4d polytopes"
authors = ["Andrew <mail@awmacpherson.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.22.3"
polytope = "^0.2.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
